repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3 # https://github.com/pre-commit/mirrors-isort/tags
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 21.10b0 # https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1 # https://github.com/pre-commit/mirrors-prettier/tags
    hooks:
      - id: prettier
