repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0 # https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3.11 # Should be a command that runs python3.6+
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.269 # https://github.com/charliermarsh/ruff/tags
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1 # https://github.com/pre-commit/mirrors-prettier/tags
    hooks:
      - id: prettier
