name: build
on:
  push:
    branches:
      - master

env:
  # Task vars
  python-version: 3.9
  poetry-version: 1.1.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code repo
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: ${{ env.poetry-version }}
      - name: Download poetry cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-2-
      - name: Install python dependencies
        run: poetry install --no-root
      - name: Clone content repo
        uses: actions/checkout@v2
        with:
          repository: newtheatre/history-project
          path: content
      - name: Build content database
        run: poetry run python nthp load
      - name: Report database stats
        run: poetry run python nthp stats
      - name: Build API
        run: poetry run python nthp dump
      - name: Deploy to S3
        run: bin/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
