name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  # Task vars
  python-version: 3.11
  poetry-version: 1.5.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code repo
        uses: actions/checkout@v3
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ env.poetry-version }}
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: poetry
      - name: Install python dependencies
        run: poetry install --no-root
      - name: Clone content repo
        uses: actions/checkout@v3
        with:
          repository: newtheatre/history-project
          path: content
      - name: Download SmugMug cache
        uses: actions/cache@v3
        with:
          path: nthp.smug.db
          key: smugmug-1
      - name: Fetch SmugMug data if not cached
        run: wget -nc https://nthp-seed.s3.eu-west-2.amazonaws.com/nthp.smug.db
      - name: Build content database
        run: poetry run python nthp load content
      - name: Report database stats
        run: poetry run python nthp stats
      - name: Enrich content database with SmugMug data
        env:
          SMUGMUG_API_KEY: ${{ secrets.SMUGMUG_API_KEY }}
        run: poetry run python nthp smug
      - name: Build API
        run: poetry run python nthp dump
      - name: Deploy to S3
        run: bin/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
