name: test
on: [push, pull_request]

env:
  # Task vars
  python-version: 3.11

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync
      - uses: actions/checkout@v4
        with:
          repository: newtheatre/history-project
          path: content
      - run: PYTHONPATH=nthp_api uv run pytest

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv sync
      - run: uv run mypy
